version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4

    steps:
      - checkout
      - run: go version
      - run: go build oya.go
      - run: ./oya run develop
      - run: ./oya run importTestKeys
      - run: ./oya run test -t "~@nocircleci"
      - run: ./oya run removeTestKeys
